-- =========================================================================
-- V1: Core Foundation - Departments, Teams, Users, RBAC, and Audit Logs
-- =========================================================================

-- 1. DEPARTMENTS Table
CREATE TABLE DEPARTMENTS (
    ID BIGINT AUTO_INCREMENT,
    NAME NVARCHAR(150) NOT NULL,
    CODE NVARCHAR(50) NOT NULL,
    MANAGER_ID BIGINT,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (ID),
    CONSTRAINT UK_DEPARTMENTS_CODE UNIQUE (CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. TEAMS Table
CREATE TABLE TEAMS (
    ID BIGINT AUTO_INCREMENT,
    NAME NVARCHAR(150) NOT NULL,
    DEPARTMENT_ID BIGINT NOT NULL,
    TEAM_LEAD_ID BIGINT,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_TEAMS PRIMARY KEY (ID),
    CONSTRAINT FK_TEAMS_DEPARTMENTS FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. USERS Table
CREATE TABLE USERS (
    ID BIGINT AUTO_INCREMENT,
    USERNAME NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(255) NOT NULL,
    PASSWORD_HASH NVARCHAR(255) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    MFA_SECRET NVARCHAR(128),
    MFA_ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
    DEPARTMENT_ID BIGINT,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY (ID),
    CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT FK_USERS_DEPARTMENTS FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Add self-referencing and cross-table foreign keys that couldn't be created inline
ALTER TABLE DEPARTMENTS ADD CONSTRAINT FK_DEPARTMENTS_USERS FOREIGN KEY (MANAGER_ID) REFERENCES USERS(ID) ON DELETE SET NULL;
ALTER TABLE TEAMS ADD CONSTRAINT FK_TEAMS_USERS FOREIGN KEY (TEAM_LEAD_ID) REFERENCES USERS(ID) ON DELETE SET NULL;

-- 4. USER_PROFILES Table
CREATE TABLE USER_PROFILES (
    ID BIGINT AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    FIRST_NAME NVARCHAR(100) NOT NULL,
    LAST_NAME NVARCHAR(100) NOT NULL,
    PHONE NVARCHAR(50),
    AVATAR_URL NVARCHAR(500),
    PREFERRED_LANGUAGE NVARCHAR(10) DEFAULT 'en',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_USER_PROFILES PRIMARY KEY (ID),
    CONSTRAINT UK_USER_PROFILES_USER UNIQUE (USER_ID),
    CONSTRAINT FK_USER_PROFILES_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. ROLES Table
CREATE TABLE ROLES (
    ID BIGINT AUTO_INCREMENT,
    NAME NVARCHAR(100) NOT NULL,
    DESCRIPTION NVARCHAR(255),
    IS_SYSTEM_DEFAULT BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ROLES PRIMARY KEY (ID),
    CONSTRAINT UK_ROLES_NAME UNIQUE (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. PERMISSIONS Table
CREATE TABLE PERMISSIONS (
    ID BIGINT AUTO_INCREMENT,
    PERM_KEY NVARCHAR(100) NOT NULL,
    DESCRIPTION NVARCHAR(255),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PERMISSIONS PRIMARY KEY (ID),
    CONSTRAINT UK_PERMISSIONS_KEY UNIQUE (PERM_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. USER_ROLES Junction Table
CREATE TABLE USER_ROLES (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    CONSTRAINT PK_USER_ROLES PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLES_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_ROLES_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. ROLE_PERMISSIONS Junction Table
CREATE TABLE ROLE_PERMISSIONS (
    ROLE_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    CONSTRAINT PK_ROLE_PERMISSIONS PRIMARY KEY (ROLE_ID, PERMISSION_ID),
    CONSTRAINT FK_ROLE_PERMISSIONS_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ROLE_PERMISSIONS_PERMISSIONS FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 9. AUDIT_LOGS Table
CREATE TABLE AUDIT_LOGS (
    ID BIGINT AUTO_INCREMENT,
    USER_ID BIGINT,
    ACTION NVARCHAR(100) NOT NULL,
    ENTITY_NAME NVARCHAR(100) NOT NULL,
    ENTITY_ID BIGINT NOT NULL,
    OLD_VALUES NVARCHAR(4000), -- JSON representation
    NEW_VALUES NVARCHAR(4000), -- JSON representation
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_AUDIT_LOGS PRIMARY KEY (ID),
    CONSTRAINT FK_AUDIT_LOGS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 10. LOGIN_LOGS Table
CREATE TABLE LOGIN_LOGS (
    ID BIGINT AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    IP_ADDRESS NVARCHAR(50) NOT NULL,
    USER_AGENT NVARCHAR(255),
    MFA_VERIFIED BOOLEAN NOT NULL DEFAULT FALSE,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_LOGIN_LOGS PRIMARY KEY (ID),
    CONSTRAINT FK_LOGIN_LOGS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================================================================
-- SEED DATA
-- =========================================================================

-- Insert Roles
INSERT INTO ROLES (NAME, DESCRIPTION, IS_SYSTEM_DEFAULT) VALUES
('USER', 'End user - raises and tracks tickets', true),
('SUPPORT_AGENT', 'Support agent - manages incidents', true),
('TEAM_LEAD', 'Team Lead - manages team ticket assignment and approvals', true),
('ADMINISTRATOR', 'Administrator - manages users, SLA and system settings', true),
('SUPER_ADMIN', 'Super Admin - manages dropdowns and system configuration', true),
('ULTRA_SUPER_ADMIN', 'Ultra Super Admin - full control and access management', true);

-- Insert Core Permissions
INSERT INTO PERMISSIONS (PERM_KEY, DESCRIPTION) VALUES
('READ_TICKETS', 'View tickets assigned to the user or their department'),
('WRITE_TICKETS', 'Create and update tickets'),
('ASSIGN_TICKETS', 'Assign tickets to team members'),
('APPROVE_REQUESTS', 'Approve service and change requests'),
('MANAGE_USERS', 'Create, update, disable users'),
('MANAGE_SYSTEM', 'Manage system configurations and properties');

-- Map Permissions to Roles
-- USER permissions
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID) VALUES
(1, 1), -- READ_TICKETS
(1, 2); -- WRITE_TICKETS

-- SUPPORT_AGENT permissions
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID) VALUES
(2, 1),
(2, 2);

-- TEAM_LEAD permissions
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID) VALUES
(3, 1),
(3, 2),
(3, 3), -- ASSIGN_TICKETS
(3, 4); -- APPROVE_REQUESTS

-- ADMINISTRATOR permissions
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID) VALUES
(4, 1),
(4, 2),
(4, 3),
(4, 4),
(4, 5); -- MANAGE_USERS

-- SUPER_ADMIN permissions
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID) VALUES
(5, 1),
(5, 2),
(5, 3),
(5, 4),
(5, 5),
(5, 6); -- MANAGE_SYSTEM

-- ULTRA_SUPER_ADMIN permissions
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID) VALUES
(6, 1),
(6, 2),
(6, 3),
(6, 4),
(6, 5),
(6, 6);
