-- =========================================================================
-- V2: Phase 2 Operations & Communication - Notifications, Emails, SLAs, Tickets
-- =========================================================================

-- 1. NOTIFICATIONS Table
CREATE TABLE NOTIFICATIONS (
    ID BIGINT AUTO_INCREMENT,
    RECIPIENT_ID BIGINT NOT NULL,
    TITLE NVARCHAR(255) NOT NULL,
    MESSAGE NVARCHAR(2000) NOT NULL,
    IS_READ BOOLEAN NOT NULL DEFAULT FALSE,
    TYPE NVARCHAR(50) NOT NULL,
    SENT_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_NOTIFICATIONS PRIMARY KEY (ID),
    CONSTRAINT FK_NOTIFICATIONS_USERS FOREIGN KEY (RECIPIENT_ID) REFERENCES USERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. EMAIL_INBOXES Table
CREATE TABLE EMAIL_INBOXES (
    ID BIGINT AUTO_INCREMENT,
    EMAIL_ADDRESS NVARCHAR(255) NOT NULL,
    IMAP_HOST NVARCHAR(255) NOT NULL,
    IMAP_PORT INT NOT NULL,
    IMAP_USER NVARCHAR(255) NOT NULL,
    IMAP_PASS NVARCHAR(255) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_EMAIL_INBOXES PRIMARY KEY (ID),
    CONSTRAINT UK_EMAIL_INBOXES_EMAIL UNIQUE (EMAIL_ADDRESS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. EMAIL_LOGS Table
CREATE TABLE EMAIL_LOGS (
    ID BIGINT AUTO_INCREMENT,
    DIRECTION NVARCHAR(10) NOT NULL, -- INBOUND / OUTBOUND
    SENDER NVARCHAR(255) NOT NULL,
    RECIPIENT NVARCHAR(255) NOT NULL,
    SUBJECT NVARCHAR(500),
    BODY_HTML NVARCHAR(4000),
    STATUS NVARCHAR(50) NOT NULL, -- SENT, FAILED, PARSED
    ERROR_MESSAGE NVARCHAR(1000),
    SENT_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_EMAIL_LOGS PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. SLA_POLICIES Table
CREATE TABLE SLA_POLICIES (
    ID BIGINT AUTO_INCREMENT,
    NAME NVARCHAR(150) NOT NULL,
    PRIORITY NVARCHAR(50) NOT NULL, -- CRITICAL, HIGH, MEDIUM, LOW
    RESPONSE_TIME_MINS INT NOT NULL,
    RESOLUTION_TIME_MINS INT NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SLA_POLICIES PRIMARY KEY (ID),
    CONSTRAINT UK_SLA_POLICIES_PRIORITY UNIQUE (PRIORITY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. TICKETS Table
CREATE TABLE TICKETS (
    ID BIGINT AUTO_INCREMENT,
    TICKET_NUMBER NVARCHAR(50) NOT NULL,
    TITLE NVARCHAR(255) NOT NULL,
    DESCRIPTION NVARCHAR(4000) NOT NULL,
    STATUS NVARCHAR(50) NOT NULL, -- NEW, OPEN, IN_PROGRESS, ON_HOLD, RESOLVED, CLOSED, CANCELLED
    PRIORITY NVARCHAR(50) NOT NULL, -- CRITICAL, HIGH, MEDIUM, LOW
    SOURCE NVARCHAR(50) NOT NULL, -- WEB, EMAIL, CHAT, API
    REQUESTER_ID BIGINT NOT NULL,
    ASSIGNED_TEAM_ID BIGINT,
    ASSIGNED_USER_ID BIGINT,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_TICKETS PRIMARY KEY (ID),
    CONSTRAINT UK_TICKETS_NUMBER UNIQUE (TICKET_NUMBER),
    CONSTRAINT FK_TICKETS_REQUESTER FOREIGN KEY (REQUESTER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_TICKETS_TEAMS FOREIGN KEY (ASSIGNED_TEAM_ID) REFERENCES TEAMS(ID) ON DELETE SET NULL,
    CONSTRAINT FK_TICKETS_USERS FOREIGN KEY (ASSIGNED_USER_ID) REFERENCES USERS(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. TICKET_WATCHERS Junction Table
CREATE TABLE TICKET_WATCHERS (
    TICKET_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CONSTRAINT PK_TICKET_WATCHERS PRIMARY KEY (TICKET_ID, USER_ID),
    CONSTRAINT FK_WATCHERS_TICKETS FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_WATCHERS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. TICKET_SLA_TRACKING Table
CREATE TABLE TICKET_SLA_TRACKING (
    ID BIGINT AUTO_INCREMENT,
    TICKET_ID BIGINT NOT NULL,
    SLA_POLICY_ID BIGINT NOT NULL,
    RESPONSE_DEADLINE DATETIME NOT NULL,
    RESOLUTION_DEADLINE DATETIME NOT NULL,
    RESPONDED_AT DATETIME,
    RESOLVED_AT DATETIME,
    IS_RESPONSE_BREACHED BOOLEAN NOT NULL DEFAULT FALSE,
    IS_RESOLUTION_BREACHED BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT PK_TICKET_SLA_TRACKING PRIMARY KEY (ID),
    CONSTRAINT FK_SLA_TRACKING_TICKETS FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_SLA_TRACKING_SLA_POLICIES FOREIGN KEY (SLA_POLICY_ID) REFERENCES SLA_POLICIES(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- =========================================================================
-- INDEXING STRATEGY
-- =========================================================================
CREATE INDEX IDX_NOTIFICATIONS_RECIPIENT ON NOTIFICATIONS(RECIPIENT_ID);
CREATE INDEX IDX_NOTIFICATIONS_IS_READ ON NOTIFICATIONS(IS_READ);
CREATE INDEX IDX_TICKETS_NUMBER ON TICKETS(TICKET_NUMBER);
CREATE INDEX IDX_TICKETS_STATUS ON TICKETS(STATUS);
CREATE INDEX IDX_TICKETS_REQUESTER ON TICKETS(REQUESTER_ID);
CREATE INDEX IDX_TICKETS_ASSIGNED_USER ON TICKETS(ASSIGNED_USER_ID);
CREATE INDEX IDX_TICKETS_ASSIGNED_TEAM ON TICKETS(ASSIGNED_TEAM_ID);
CREATE INDEX IDX_SLA_TRACKING_TICKET ON TICKET_SLA_TRACKING(TICKET_ID);

-- =========================================================================
-- SEED SLA POLICIES
-- =========================================================================
INSERT INTO SLA_POLICIES (NAME, PRIORITY, RESPONSE_TIME_MINS, RESOLUTION_TIME_MINS) VALUES
('P1 - Critical Priority Policy', 'CRITICAL', 30, 240),     -- 30 min response, 4 hour resolution
('P2 - High Priority Policy', 'HIGH', 120, 480),          -- 2 hour response, 8 hour resolution
('P3 - Medium Priority Policy', 'MEDIUM', 480, 1440),     -- 8 hour response, 24 hour resolution
('P4 - Low Priority Policy', 'LOW', 1440, 2880);          -- 24 hour response, 48 hour resolution
