-- =========================================================================
-- V3: Phase 3 ITSM Process Lifecycle - Incident, Problem, Change, Service Requests, approvals
-- =========================================================================

-- 1. INCIDENTS Table
CREATE TABLE INCIDENTS (
    ID BIGINT AUTO_INCREMENT,
    IMPACT NVARCHAR(50) NOT NULL,
    URGENCY NVARCHAR(50) NOT NULL,
    CATEGORY NVARCHAR(100) NOT NULL,
    SUBCATEGORY NVARCHAR(100),
    MAJOR_INCIDENT BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT PK_INCIDENTS PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. INCIDENT_TICKETS Table
CREATE TABLE INCIDENT_TICKETS (
    INCIDENT_ID BIGINT NOT NULL,
    TICKET_ID BIGINT NOT NULL,
    CONSTRAINT PK_INCIDENT_TICKETS PRIMARY KEY (INCIDENT_ID, TICKET_ID),
    CONSTRAINT FK_INCIDENT_TICKETS_INCIDENTS FOREIGN KEY (INCIDENT_ID) REFERENCES INCIDENTS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_INCIDENT_TICKETS_TICKETS FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. PROBLEMS Table
CREATE TABLE PROBLEMS (
    ID BIGINT AUTO_INCREMENT,
    TITLE NVARCHAR(255) NOT NULL,
    DESCRIPTION NVARCHAR(4000) NOT NULL,
    ROOT_CAUSE NVARCHAR(4000),
    WORKAROUND NVARCHAR(4000),
    RESOLUTION NVARCHAR(4000),
    STATUS NVARCHAR(50) NOT NULL, -- OPEN, INVESTIGATING, RESOLVED, CLOSED
    OWNER_ID BIGINT,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PROBLEMS PRIMARY KEY (ID),
    CONSTRAINT FK_PROBLEMS_USERS FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. PROBLEM_INCIDENTS Table
CREATE TABLE PROBLEM_INCIDENTS (
    PROBLEM_ID BIGINT NOT NULL,
    INCIDENT_ID BIGINT NOT NULL,
    CONSTRAINT PK_PROBLEM_INCIDENTS PRIMARY KEY (PROBLEM_ID, INCIDENT_ID),
    CONSTRAINT FK_PROBLEM_INCIDENTS_PROBLEMS FOREIGN KEY (PROBLEM_ID) REFERENCES PROBLEMS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_PROBLEM_INCIDENTS_INCIDENTS FOREIGN KEY (INCIDENT_ID) REFERENCES INCIDENTS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. CHANGES Table
CREATE TABLE CHANGES (
    ID BIGINT AUTO_INCREMENT,
    TITLE NVARCHAR(255) NOT NULL,
    DESCRIPTION NVARCHAR(4000) NOT NULL,
    CHANGE_TYPE NVARCHAR(50) NOT NULL, -- STANDARD, NORMAL, EMERGENCY
    RISK_LEVEL NVARCHAR(50) NOT NULL,
    STATUS NVARCHAR(50) NOT NULL, -- DRAFT, CAB_APPROVAL, SCHEDULED, IMPLEMENTING, REVIEW, CLOSED
    ROLLBACK_PLAN NVARCHAR(4000) NOT NULL,
    TEST_PLAN NVARCHAR(4000) NOT NULL,
    PLANNED_START DATETIME NOT NULL,
    PLANNED_END DATETIME NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CHANGES PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. CHANGE_TICKET_LINKS Table
CREATE TABLE CHANGE_TICKET_LINKS (
    CHANGE_ID BIGINT NOT NULL,
    TICKET_ID BIGINT NOT NULL,
    CONSTRAINT PK_CHANGE_TICKET_LINKS PRIMARY KEY (CHANGE_ID, TICKET_ID),
    CONSTRAINT FK_CHANGE_LINKS_CHANGES FOREIGN KEY (CHANGE_ID) REFERENCES CHANGES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_CHANGE_LINKS_TICKETS FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. SERVICE_CATALOG_ITEMS Table
CREATE TABLE SERVICE_CATALOG_ITEMS (
    ID BIGINT AUTO_INCREMENT,
    NAME NVARCHAR(150) NOT NULL,
    DESCRIPTION NVARCHAR(1000) NOT NULL,
    CATEGORY NVARCHAR(100) NOT NULL,
    COST DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_SERVICE_CATALOG_ITEMS PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. SERVICE_REQUESTS Table
CREATE TABLE SERVICE_REQUESTS (
    ID BIGINT AUTO_INCREMENT,
    TICKET_ID BIGINT NOT NULL,
    CATALOG_ITEM_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 1,
    TOTAL_COST DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_SERVICE_REQUESTS PRIMARY KEY (ID),
    CONSTRAINT FK_SERVICE_REQUESTS_TICKETS FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_SERVICE_REQUESTS_ITEMS FOREIGN KEY (CATALOG_ITEM_ID) REFERENCES SERVICE_CATALOG_ITEMS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 9. APPROVAL_POLICIES Table
CREATE TABLE APPROVAL_POLICIES (
    ID BIGINT AUTO_INCREMENT,
    NAME NVARCHAR(150) NOT NULL,
    ENTITY_TYPE NVARCHAR(50) NOT NULL, -- CHANGE, REQUEST
    MIN_AMOUNT DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    CONSTRAINT PK_APPROVAL_POLICIES PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 10. APPROVAL_STEPS Table
CREATE TABLE APPROVAL_STEPS (
    ID BIGINT AUTO_INCREMENT,
    POLICY_ID BIGINT NOT NULL,
    APPROVER_ROLE_ID BIGINT NOT NULL,
    STEP_ORDER INT NOT NULL,
    CONSTRAINT PK_APPROVAL_STEPS PRIMARY KEY (ID),
    CONSTRAINT FK_APPROVAL_STEPS_POLICIES FOREIGN KEY (POLICY_ID) REFERENCES APPROVAL_POLICIES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_APPROVAL_STEPS_ROLES FOREIGN KEY (APPROVER_ROLE_ID) REFERENCES ROLES(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 11. APPROVAL_REQUESTS Table
CREATE TABLE APPROVAL_REQUESTS (
    ID BIGINT AUTO_INCREMENT,
    POLICY_ID BIGINT NOT NULL,
    ENTITY_ID BIGINT NOT NULL, -- References ID of target CHANGE or SERVICE_REQUEST
    APPROVER_ID BIGINT,
    STATUS NVARCHAR(50) NOT NULL, -- PENDING, APPROVED, REJECTED
    STEP_INDEX INT NOT NULL DEFAULT 1,
    REMARKS NVARCHAR(1000),
    DECIDED_AT DATETIME,
    CONSTRAINT PK_APPROVAL_REQUESTS PRIMARY KEY (ID),
    CONSTRAINT FK_APPROVAL_REQUESTS_POLICIES FOREIGN KEY (POLICY_ID) REFERENCES APPROVAL_POLICIES(ID),
    CONSTRAINT FK_APPROVAL_REQUESTS_USERS FOREIGN KEY (APPROVER_ID) REFERENCES USERS(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
