-- =========================================================================
-- V4: Phase 4 CMDB & Asset Management - Vendors, Assets, CIs, Relationships
-- =========================================================================

-- 1. VENDORS Table
CREATE TABLE VENDORS (
    ID BIGINT AUTO_INCREMENT,
    COMPANY_NAME NVARCHAR(150) NOT NULL,
    CONTACT_NAME NVARCHAR(150),
    EMAIL NVARCHAR(255),
    PHONE NVARCHAR(50),
    STATUS NVARCHAR(50) NOT NULL, -- ACTIVE, INACTIVE, BLACKLISTED
    CONSTRAINT PK_VENDORS PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. ASSETS Table
CREATE TABLE ASSETS (
    ID BIGINT AUTO_INCREMENT,
    ASSET_TAG NVARCHAR(100) NOT NULL,
    NAME NVARCHAR(150) NOT NULL,
    SERIAL_NUMBER NVARCHAR(150),
    MODEL NVARCHAR(150),
    ASSET_TYPE NVARCHAR(50) NOT NULL, -- HARDWARE, SOFTWARE, LICENSE
    STATUS NVARCHAR(50) NOT NULL, -- IN_STOCK, IN_USE, RETIRED, LOST, REPAIR
    VENDOR_ID BIGINT,
    PURCHASE_DATE DATE,
    WARRANTY_EXPIRY DATE,
    COST DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_ASSETS PRIMARY KEY (ID),
    CONSTRAINT UK_ASSETS_TAG UNIQUE (ASSET_TAG),
    CONSTRAINT FK_ASSETS_VENDORS FOREIGN KEY (VENDOR_ID) REFERENCES VENDORS(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. CONFIGURATION_ITEMS Table
CREATE TABLE CONFIGURATION_ITEMS (
    ID BIGINT AUTO_INCREMENT,
    NAME NVARCHAR(150) NOT NULL,
    CI_TYPE NVARCHAR(100) NOT NULL, -- DATABASE, SERVER, ROUTER, WEB_SERVICE
    IP_ADDRESS NVARCHAR(50),
    ENVIRONMENT NVARCHAR(50) NOT NULL, -- PROD, STAGE, DEV
    OWNER_USER_ID BIGINT,
    ASSET_ID BIGINT,
    CONSTRAINT PK_CONFIGURATION_ITEMS PRIMARY KEY (ID),
    CONSTRAINT FK_CI_USERS FOREIGN KEY (OWNER_USER_ID) REFERENCES USERS(ID) ON DELETE SET NULL,
    CONSTRAINT FK_CI_ASSETS FOREIGN KEY (ASSET_ID) REFERENCES ASSETS(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. CI_RELATIONSHIPS Table
CREATE TABLE CI_RELATIONSHIPS (
    ID BIGINT AUTO_INCREMENT,
    PARENT_CI_ID BIGINT NOT NULL,
    CHILD_CI_ID BIGINT NOT NULL,
    RELATIONSHIP_TYPE NVARCHAR(100) NOT NULL, -- DEPENDS_ON, RUNS_ON, INSTALLED_ON
    CONSTRAINT PK_CI_RELATIONSHIPS PRIMARY KEY (ID),
    CONSTRAINT FK_CI_REL_PARENT FOREIGN KEY (PARENT_CI_ID) REFERENCES CONFIGURATION_ITEMS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_CI_REL_CHILD FOREIGN KEY (CHILD_CI_ID) REFERENCES CONFIGURATION_ITEMS(ID) ON DELETE CASCADE,
    CONSTRAINT CK_CI_RELATIONSHIPS_PREVENT_SELF_REF CHECK (PARENT_CI_ID <> CHILD_CI_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
