-- =========================================================================
-- V5: Phase 5 Knowledge Base, GRC, and Billing Subscriptions
-- =========================================================================

-- 1. KB_CATEGORIES Table
CREATE TABLE KB_CATEGORIES (
    ID BIGINT AUTO_INCREMENT,
    NAME NVARCHAR(150) NOT NULL,
    DESCRIPTION NVARCHAR(500),
    PARENT_ID BIGINT,
    CONSTRAINT PK_KB_CATEGORIES PRIMARY KEY (ID),
    CONSTRAINT FK_KB_CATEGORIES_PARENT FOREIGN KEY (PARENT_ID) REFERENCES KB_CATEGORIES(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. KB_ARTICLES Table
CREATE TABLE KB_ARTICLES (
    ID BIGINT AUTO_INCREMENT,
    CATEGORY_ID BIGINT NOT NULL,
    TITLE NVARCHAR(255) NOT NULL,
    CONTENT NVARCHAR(4000) NOT NULL, -- Markdown/HTML content
    STATUS NVARCHAR(50) NOT NULL, -- DRAFT, UNDER_REVIEW, PUBLISHED
    AUTHOR_ID BIGINT NOT NULL,
    VIEW_COUNT INT NOT NULL DEFAULT 0,
    IS_PINNED BOOLEAN NOT NULL DEFAULT FALSE,
    PUBLISHED_AT DATETIME,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME,
    CONSTRAINT PK_KB_ARTICLES PRIMARY KEY (ID),
    CONSTRAINT FK_KB_ARTICLES_CATEGORIES FOREIGN KEY (CATEGORY_ID) REFERENCES KB_CATEGORIES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_KB_ARTICLES_USERS FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. SECURITY_INCIDENTS Table
CREATE TABLE SECURITY_INCIDENTS (
    ID BIGINT AUTO_INCREMENT,
    INCIDENT_NUMBER NVARCHAR(50) NOT NULL,
    TITLE NVARCHAR(255) NOT NULL,
    DESCRIPTION NVARCHAR(4000) NOT NULL,
    SEVERITY NVARCHAR(50) NOT NULL, -- CRITICAL, HIGH, MEDIUM, LOW
    STATUS NVARCHAR(50) NOT NULL, -- OPEN, INVESTIGATING, RESOLVED, CLOSED
    IDENTIFIED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SECURITY_INCIDENTS PRIMARY KEY (ID),
    CONSTRAINT UK_SECURITY_INCIDENTS_NUMBER UNIQUE (INCIDENT_NUMBER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. SUBSCRIPTIONS Table
CREATE TABLE SUBSCRIPTIONS (
    ID BIGINT AUTO_INCREMENT,
    PLAN_TIER NVARCHAR(50) NOT NULL, -- FREE, STARTER, PROFESSIONAL, ENTERPRISE
    STATUS NVARCHAR(50) NOT NULL, -- ACTIVE, TRIALING, PAST_DUE, CANCELED
    BILLING_CYCLE NVARCHAR(50) NOT NULL, -- MONTHLY, ANNUAL
    CURRENT_PERIOD_START DATETIME NOT NULL,
    CURRENT_PERIOD_END DATETIME NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME,
    CONSTRAINT PK_SUBSCRIPTIONS PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
