-- =========================================================================
-- V6: Ticket Detail Extensions and Settings Configuration
-- =========================================================================

-- 1. TICKET_COMMENTS Table
CREATE TABLE TICKET_COMMENTS (
    ID BIGINT AUTO_INCREMENT,
    TICKET_ID BIGINT NOT NULL,
    AUTHOR_ID BIGINT NOT NULL,
    BODY NVARCHAR(4000) NOT NULL,
    IS_INTERNAL BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TICKET_COMMENTS PRIMARY KEY (ID),
    CONSTRAINT FK_COMMENTS_TICKETS FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_COMMENTS_USERS FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. TICKET_ACTIVITIES Table
CREATE TABLE TICKET_ACTIVITIES (
    ID BIGINT AUTO_INCREMENT,
    TICKET_ID BIGINT NOT NULL,
    ACTOR_ID BIGINT,
    ACTIVITY_TYPE NVARCHAR(80) NOT NULL, -- STATUS_CHANGE, ASSIGNED, COMMENT_ADDED, SLA_BREACHED
    OLD_VALUE NVARCHAR(255),
    NEW_VALUE NVARCHAR(255),
    DESCRIPTION NVARCHAR(500),
    OCCURRED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TICKET_ACTIVITIES PRIMARY KEY (ID),
    CONSTRAINT FK_ACTIVITIES_TICKETS FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ACTIVITIES_USERS FOREIGN KEY (ACTOR_ID) REFERENCES USERS(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IDX_COMMENTS_TICKET ON TICKET_COMMENTS(TICKET_ID);
CREATE INDEX IDX_ACTIVITIES_TICKET ON TICKET_ACTIVITIES(TICKET_ID);

-- 3. SETTINGS Table
CREATE TABLE SETTINGS (
    ID BIGINT AUTO_INCREMENT,
    SETTING_KEY NVARCHAR(100) NOT NULL,
    SETTING_VALUE NVARCHAR(1000),
    FIELD_TYPE NVARCHAR(50) NOT NULL DEFAULT 'TEXT',  -- TEXT, BOOLEAN, NUMBER, JSON
    LABEL NVARCHAR(200) NOT NULL,
    SECTION NVARCHAR(100) NOT NULL,  -- GENERAL, SLA, NOTIFICATIONS, BRANDING
    CONSTRAINT PK_SETTINGS PRIMARY KEY (ID),
    CONSTRAINT UK_SETTINGS_KEY UNIQUE (SETTING_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed default settings
INSERT INTO SETTINGS (SETTING_KEY, SETTING_VALUE, FIELD_TYPE, LABEL, SECTION) VALUES
('org.name', 'ConnectIT Corp', 'TEXT', 'Organization Name', 'GENERAL'),
('org.timezone', 'Asia/Kolkata', 'TEXT', 'Default Timezone', 'GENERAL'),
('ticket.prefix', 'TKT', 'TEXT', 'Ticket Number Prefix', 'GENERAL'),
('sla.business_hours_only', 'false', 'BOOLEAN', 'SLA counts only during business hours', 'SLA'),
('notifications.email_enabled', 'false', 'BOOLEAN', 'Enable Email Notifications', 'NOTIFICATIONS'),
('notifications.sla_alert_mins', '30', 'NUMBER', 'Alert before SLA breach (minutes)', 'NOTIFICATIONS');
