-- =========================================================================
-- V8: Employee Master, Manager Hierarchy, and User Provisioning Link
-- =========================================================================

-- 1. Create EMPLOYEES Table (Employee Master)
CREATE TABLE EMPLOYEES (
    ID BIGINT AUTO_INCREMENT,
    COMPANY_ID BIGINT NOT NULL,
    EMPLOYEE_CODE VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    PHONE VARCHAR(50),
    DEPARTMENT_ID BIGINT,
    JOB_TITLE VARCHAR(100),
    STATUS VARCHAR(50) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, INACTIVE, LEAVE, TERMINATED
    MANAGER_ID BIGINT,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (ID),
    CONSTRAINT UK_EMPLOYEE_CODE UNIQUE (COMPANY_ID, EMPLOYEE_CODE),
    CONSTRAINT UK_EMPLOYEE_EMAIL UNIQUE (COMPANY_ID, EMAIL),
    CONSTRAINT FK_EMPLOYEES_COMPANIES FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_EMPLOYEES_DEPARTMENTS FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID) ON DELETE SET NULL,
    CONSTRAINT FK_EMPLOYEES_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Modify USERS to support Employee mapping and force password reset
ALTER TABLE USERS ADD COLUMN EMPLOYEE_ID BIGINT UNIQUE;
ALTER TABLE USERS ADD COLUMN PASSWORD_RESET_REQUIRED BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE USERS ADD CONSTRAINT FK_USERS_EMPLOYEES FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID) ON DELETE SET NULL;

-- 3. Automatically migrate existing Users into Employee records to preserve data integrity
INSERT INTO EMPLOYEES (COMPANY_ID, EMPLOYEE_CODE, FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID, STATUS)
SELECT 
    u.COMPANY_ID,
    CONCAT('EMP-', u.ID) AS EMPLOYEE_CODE,
    COALESCE(p.FIRST_NAME, u.USERNAME) AS FIRST_NAME,
    COALESCE(p.LAST_NAME, 'Employee') AS LAST_NAME,
    u.EMAIL,
    u.DEPARTMENT_ID,
    CASE WHEN u.IS_ACTIVE = 1 THEN 'ACTIVE' ELSE 'INACTIVE' END AS STATUS
FROM USERS u
LEFT JOIN USER_PROFILES p ON u.ID = p.USER_ID;

-- 4. Update USERS to link to the newly created Employee records
UPDATE USERS u
JOIN EMPLOYEES e ON u.EMAIL = e.EMAIL AND u.COMPANY_ID = e.COMPANY_ID
SET u.EMPLOYEE_ID = e.ID;
